from customtkinter import *
import tkinter as tk
import mysql.connector as mysql
def Validate():
    ValidSuccess()
    conn = mysql.connect(host = 'localhost',database = 'eCare', user = 'root', password = "")
    cur = conn.cursor()
    cur.execute("SELECT * FROM USER WHERE USERNAME = '%s';",UserName.get())
    if len(cur.fetchall()) != 0:
        GenErr(0)
    if Password.get() == "" or ConfirmPassword.get() == "":
        GenErr(1)
    if Password.get() != ConfirmPassword.get():
        GenErr(2)
    if Choice.get() == 1:
        cur.execute("SELECT * FROM USER WHERE USERNAME = '%s;'", Vigilante.get())
        if len(cur.fetchall()) != 1:
            GenErr(3)
    cur.execute("INSERT INTO USER (FULL_NAME,USERNAME,PASSWORD,AGE) VALUES ( %s, %s, %s, %s);",(FullName.get(),UserName.get(),Password.get(),int(Age.get())))
    if Choice.get() == 1:
        cur.execute("SELECT USER_ID FROM USER WHERE USERNAME = '%s';",UserName.get())
        UID = cur.fetchone()
        cur.execute("SELECT USER_ID FROM USER WHERE USERNAME = '%s';",Vigilante.get())
        VID = cur.fetchone()
        cur.execute("INSERT INTO VIGILANTE (USER_ID,VIGILANTE_ID) VALUES (%s, %s);",(UID,VID))
    conn.commit()
    cur.close()
    conn.close()
def Insert():
    conn = mysql.connect(host = 'localhost',database = 'eCare', user = 'root', password = "")
    cur = conn.cursor()
    cur.execute("SELECT * FROM USER;")
    for row in cur.fetchall():
        print(row)
    conn.commit()
    cur.close()
    conn.close()
def GenErr(ErrCode):
    if ErrCode == 0:
        UserNameErr.grid()
        Username.configure(border_color = "red")
    elif ErrCode == 1:
        PasswordErr.grid()
        Password.configure(border_color = "red")
    elif ErrCode == 2:
        ConfirmPasswordErr.grid()
        ConfirmPassword.configure(border_color = "red")
    elif ErrCode == 3:
        VigilanteErr.grid()
        Vigilante.configure(border_color = "red")
def ValidSuccess():
    #['#979DA2', '#565B5E']
    UserNameErr.grid_remove()
    UserName.configure(border_color = ('#979DA2', '#565B5E'))
    PasswordErr.grid_remove()
    Password.configure(border_color = ('#979DA2', '#565B5E'))
    ConfirmPasswordErr.grid_remove()
    ConfirmPassword.configure(border_color = ('#979DA2', '#565B5E'))
    VigilanteErr.grid_remove()
    Vigilante.configure(border_color = ('#979DA2', '#565B5E'))
def changeState():
    if Choice.get() == 1:
        Vigilante.configure(state = "normal")
        GenErr(3)
    else:
        Vigilante.configure(state = "disabled")
        ValidSuccess()
def updateAgeCount(value):
    AgeTracker.configure(text=str(value))
    if Age.get() < 18:
        Age.configure(button_color = "red", button_hover_color = "darkred")
    else:
        Age.configure(button_color = "blue", button_hover_color = "darkblue")
set_appearance_mode("Dark")
set_default_color_theme("blue")
root = CTk()
root.title("eCare")
root.geometry("1024x720")
height = root.winfo_height()
width = root.winfo_width()
signUp = CTkFrame(master = root,corner_radius = 20)
signUpScroll = CTkScrollableFrame(master = signUp,corner_radius = 20)
LabFont1 = CTkFont(family="Helvetica",size = 40,weight = "bold")
LabFont2 = CTkFont(family="Helvetica",size = 20,weight = "bold")
LabFont3 = CTkFont(family="Helvetica",size = 20,weight = "bold")
LabFont4 = CTkFont(family="Helvetica",size = 20)
LabFont5 = CTkFont(family="Helvetica",size = 15)
signUp.place(relx=0.5,rely = 0.5,relwidth = 0.8,relheight = .8,anchor = tk.CENTER)
WelcomeLab = CTkLabel(master = signUp, text = "Welcome To eCare!",font = LabFont1)
FullNameLab = CTkLabel(master = signUpScroll,text = "Full Name",font = LabFont3)
FullName = CTkEntry(master = signUpScroll,corner_radius = 10, font = LabFont3, placeholder_text = "Name")
UserNameLab = CTkLabel(master = signUpScroll,text = "Username",font = LabFont3)
UserName = CTkEntry(master = signUpScroll,corner_radius = 10, font = LabFont3, placeholder_text = "Username")
UserNameErr = CTkLabel(master = signUpScroll,text = "*The username already exists!",font = LabFont5, text_color = "red")
VigilanteErr = CTkLabel(master = signUpScroll,text = "*The username does not exists!",font = LabFont5, text_color = "red")
PasswordLab = CTkLabel(master = signUpScroll,text = "Password",font = LabFont3)
Password = CTkEntry(master = signUpScroll,corner_radius = 10, font = LabFont3, show = "*", placeholder_text = "Password")
PasswordErr = CTkLabel(master = signUpScroll,text = "*The password is mandatory!",font = LabFont5, text_color = "red")
ConfirmPasswordLab = CTkLabel(master = signUpScroll,text = "Confirm Password",font = LabFont3)
ConfirmPassword = CTkEntry(master = signUpScroll,corner_radius = 10, font = LabFont3, show = "*", placeholder_text = "Confirm Password")
ConfirmPasswordErr = CTkLabel(master = signUpScroll,text = "*This password does not match with the previous field!",font = LabFont5, text_color = "red")
AgeLab = CTkLabel(master = signUpScroll,text = "Age",font = LabFont3)
Age = CTkSlider(master = signUpScroll,corner_radius = 10,from_ = 1, to = 100, number_of_steps = 99, command = updateAgeCount, button_color = "blue", button_hover_color = "darkblue")
AgeTracker = CTkLabel(master = signUpScroll,text = str(int(Age.get())),font = LabFont3)
Choice = CTkSwitch(master = signUpScroll, text = "Do you wish to add any Vigilante?", font = LabFont4, command = changeState)
VigilanteLab = CTkLabel(master = signUpScroll, text = "Vigilante", font = LabFont3)
Vigilante = CTkEntry(master = signUpScroll, corner_radius = 10, font = LabFont3, placeholder_text = "Vigilante", state = "disabled")
Submit = CTkButton(master = signUp, text = "Create Account", fg_color = "green", hover_color = "darkgreen", font = LabFont3, command = Validate)
StartLab = CTkLabel(master = signUp, text = "Let's get you started",font = LabFont2)
WelcomeLab.place(relx = 0.5, rely = 0.1, anchor = tk.CENTER)
StartLab.place(relx = 0.5, rely = 0.18, anchor = tk.CENTER)
signUpScroll.place(relx=0.5,rely = 0.55,relwidth = 0.8,relheight = .6,anchor = tk.CENTER)
FullNameLab.grid(row = 0, column = 0, padx = 50, pady = (20,0))
FullName.grid(row = 0, column = 1, padx = 60, pady = (20,20), sticky = "WE")
UserNameLab.grid(row = 1, column = 0,  padx = 50, pady = (20,0))
UserName.grid(row = 1, column = 1, padx = 60, pady = (20,0), sticky = "WE")
UserNameErr.grid(row = 2,column = 1, padx = 60, pady = (0,20), sticky = "WE")
PasswordLab.grid(row = 3, column = 0,  padx = 50, pady = (20,0))
Password.grid(row = 3, column = 1, padx = 60, pady = (20,0), sticky = "WE")
PasswordErr.grid(row = 4, column = 1, padx = 60, pady = (0,20), sticky = "WE")
ConfirmPasswordLab.grid(row = 5, column = 0,  padx = 50, pady = (20,0))
ConfirmPassword.grid(row = 5, column = 1, padx = 60, pady = (20,0), sticky = "WE")
ConfirmPasswordErr.grid(row = 6, column = 1, padx = 60, pady = (0,20), sticky = "WE")
AgeLab.grid(row = 7, column = 0,  padx = 50, pady = (20,0))
Age.grid(row = 7, column = 1, padx = 60, pady = (20,0), sticky = "WE")
AgeTracker.grid(row = 7, column = 2, padx = 10, pady = (20,0), sticky = "WE")
Choice.grid(row = 8,column = 0, padx = 50, pady = 20, columnspan = 3)
VigilanteLab.grid(row = 9, column = 0,  padx = 50, pady = (20,0))
Vigilante.grid(row = 9, column = 1, padx = 60, pady = (20,0), sticky = "WE")
VigilanteErr.grid(row = 10, column = 1, padx = 60, pady = (0,20), sticky = "WE")
signUpScroll.grid_columnconfigure(0,weight = 0)
signUpScroll.grid_columnconfigure(1,weight = 1)
Submit.place(relx = 0.5, rely = 0.85,anchor = tk.CENTER, relwidth = 0.2)
ValidSuccess()
Insert()
root.mainloop() 
